# Generated by Django 5.0.2 on 2024-02-24 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('base_power_consumption', models.FloatField()),
                ('historical_peak_usage', models.BooleanField()),
                ('production_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MachinePowerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('power_consumption', models.FloatField()),
                ('is_peak', models.BooleanField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backapp.machine')),
            ],
        ),
    ]
