# Generated by Django 5.0.2 on 2024-03-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='historical_peak_usage',
            field=models.CharField(max_length=10),
        ),
    ]
