# Generated by Django 5.0.2 on 2024-03-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0003_machinedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinepowerhistory',
            name='machine',
            field=models.CharField(max_length=255),
        ),
    ]
