# Generated by Django 5.0.2 on 2024-03-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0004_alter_machinepowerhistory_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='historical_peak_usage',
        ),
    ]
