# Generated by Django 5.0.2 on 2024-03-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0005_remove_machine_historical_peak_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.IntegerField()),
                ('energy_output', models.FloatField()),
                ('energy_input', models.FloatField()),
                ('time_of_day', models.CharField(max_length=50)),
                ('production', models.FloatField()),
            ],
        ),
    ]
