# Generated by Django 5.0.2 on 2024-04-14 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0006_machineinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MachineInfo',
        ),
    ]
