# Generated by Django 5.0.2 on 2024-04-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0007_delete_machineinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_ids', models.CharField(max_length=255)),
                ('timestamps', models.FloatField()),
                ('current', models.FloatField()),
                ('voltage', models.FloatField()),
                ('power_consumed', models.FloatField()),
                ('useful_output', models.FloatField()),
                ('efficiency', models.FloatField()),
                ('peak_times', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='name',
            new_name='machine_ids',
        ),
    ]
