# Generated by Django 5.0.2 on 2024-04-21 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0008_machine_data_rename_name_machine_machine_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='machine_ids',
            new_name='name',
        ),
    ]
