# Generated by Django 5.0.2 on 2024-04-22 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0009_rename_machine_ids_machine_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MachineData',
        ),
    ]
