# Generated by Django 5.0.2 on 2024-04-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0010_delete_machinedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='dummy_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.IntegerField()),
                ('current', models.IntegerField()),
                ('power', models.IntegerField()),
            ],
        ),
    ]
