# Generated by Django 5.0.2 on 2024-04-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0011_dummy_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='automatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=100)),
                ('useful_output', models.FloatField()),
                ('power_consumed', models.FloatField()),
                ('efficiency', models.FloatField()),
                ('peak_time_category', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='automaticHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=100)),
                ('useful_output', models.FloatField()),
                ('power_consumed', models.FloatField()),
                ('efficiency', models.FloatField()),
                ('peak_time_category', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
